version: "2"
services:

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:0.91.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "13133:13133" # Health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "55681:55681" # OTLP HTTP receiver alternative port

  # Fish service
  fish-service:
    image: fish_demo:latest
    ports:
      - "8083:8083"
  # Mustelid service
  mustelid-service:
    image: mustelid_demo:latest
    ports:
      - "8084:8084"
  # Feline service
  feline-service:
    image: feline_demo:latest
    ports:
      - "8085:8085"
  # Mammal service
  mammal-service:
    image: mammal_demo:latest
    ports:
      - "8081:8081"
    depends_on:
      - feline-service
      - mustelid-service
  # Animal service
  animal-service:
    image: animals_demo:latest
    ports:
      - "8080:8080"
    depends_on:
      - fish-service
      - mammal-service
